name: service_provider
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # State Management
  get: ^4.6.1


  # Networking
  dio: ^4.0.6
  json_annotation: ^4.5.0
  internet_connection_checker: ^0.0.1+3

  # HW
  shared_preferences: ^2.0.15

  # Localization
  intl: ^0.17.0

  # DI
  injectable: ^1.5.3
  get_it: ^7.2.0


  # Data
  fimber: ^0.6.6
  equatable: ^2.0.3
  tuple: ^2.0.0
  freezed_annotation: ^1.1.0
  dartz: ^0.10.1

  # UI
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3
  animations: ^2.0.2
#  flutter_portal: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  build_test: ^2.1.0
  json_serializable: ^6.2.0
  injectable_generator: ^1.5.2
  flutter_lints: ^1.0.0
  freezed: ^1.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lang/

